version: "2"
services:
    server:
        build: .
        ports: 
            - "8000:8000"
        depends_on: 
            - db
        links:
            - db
        volumes:
            - ./user-content:/app/user-content
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db