version: "2"
services:
    server:
        build: .
        ports: 
            - "80:8080"
        depends_on: 
            - db
        links:
            - db
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db